config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :edit]
  resources :user_sessions, only: [:create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :active_requests, only: [:new, :edit]
  
  get '/dashboard/index', to: 'dashboard#index'
  match '/dashboard/layouts/:partial/:params', to: 'jquery#dashboard_options', via: [:get,:post]
  post '/dashboard/layouts/:partial', to: 'jquery#dashboard_options'
  get '/dashboard/payments_details', to: 'jquery#payments_details'
  get 'dashboard/layouts/:partial', to: 'static_pages#partial'
  get '/dashboard/info/getwallets', to: 'jquery#get_wallets'
  get '/dashboard/info/getpayments', to: 'jquery#get_payments'
  get '/dashboard/info/getpayment/:id', to: 'jquery#render_payment'
  get '/dashboard/info/get_withdrawal_details/:id', to: 'jquery#render_withdrawal_details'
  post '/dashboard/withdrawal/cancel/:id', to: 'jquery#cancel_withdrawal'
  post 'dashboard/confirmar_deposito', to: 'admin#confirm_saldo'
  post 'dashboard/register_users', to: 'admin#register_users'
  get '/dashboard/instant_buy_price/:coin1/:coin2/:tipo', to: 'api#instant_buy_price'
  get '/dashboard/overview/wallets/:currency', to: 'dashboard#wallets_view'
  patch '/dashboard/changepasswd', to: 'password_resets#change_pass'
  
  
  get '/exchange/pair/:coin1/:coin2', to: 'exchange#render_orders'
  post '/exchange/pair/:coin1/:coin2', to: 'exchange#create_order'
  post '/exchange/order/cancel/:id', to: 'exchange#cancel_order'
  get '/exchange/open_orders', to: 'exchange#open_orders'
  post '/exchange/instant', to: 'exchange#instant'
  post '/deposit/new', to: 'exchange#deposit_new'
  get '/deposit/verify/:id', to: 'static_pages#deposit_form'
  post '/deposit/verify/new', to: 'dashboard#deposit_verify'
  get '/deposit_detail/:id', to: 'admin#deposit_detail'
  get '/trader', to: 'static_pages#trader'
  
  match '/editInfo/bank', to: 'users#new_bank_account', via: [:get, :post]
  get 'bank/:op/:id', to: 'users#bank_operation'

  post '/active_requests/new', to: 'users#active_request_new'
  #post '/bank/account/new', to: 'users#new_bank_account'
#aliases
  get '/sign_out', to: 'user_sessions#destroy', as: :sign_out
  get '/sign_in', to: 'user_sessions#new', as: :sign_in
  
  post '/users/new', to: 'users#create'
  post '/cpay', to: 'jquery#coinpayments_deposit'
  
  get '/withdrawal/form/:currency', to: 'jquery#withdrawal_get'
  get '/withdrawal/:code', to: 'static_pages#withdrawal'
  
  
  get '/request_detail/:request_id', to: 'admin#request_details'
  post '/admin/activation', to: 'admin#active_account'
  post '/admin/deposit_confirm', to: 'admin#deposit_confirm'
  
  get '/api/is_valid_address/:currency/:address', to: 'api#test_address'
  post '/api/newKey', to: 'api#generate_api_key'
  post '/api/deleteKey/:key', to: 'api#delete_api_key'
  post '/api/:method/:message', to: 'api#proxyRequest'
  post '/api/:method', to: 'api#proxyRequest'
  
  get '/trader/:option', to: 'trader#proxyRequest'
  get '/trader/orders_history/:pair/', to: 'trader#graph'
  post '/trader/:option', to: 'trader#postRequests'
  
  namespace :api do
    namespace :public do 
      
    end
    namespace :trade do
      
    end
  end
  
  mount ActionCable.server => '/cable'
  
  post '/contact', to: 'jquery#contact_email'
  root to: 'static_pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/exchange_controller.rb
class ExchangeController < ApplicationController
    skip_before_action :verify_authenticity_token, only: [:cancel_order]
    def render_orders
        session[:currency1] = params[:coin1]
        session[:currency2] = params[:coin2]
    end
    
    def instant
        create_order(pair: params[:currency_base], amount: params[:amount], type: params[:type])
    end
    
    def deposit_new
        new_deposit = current_user.payment.new
        new_deposit.status = "incomplete"
        new_deposit.label = "deposit_operation"
        new_deposit.endereco = nil
        new_deposit.volume = params[:amount]
        new_deposit.network = "BRL"
        new_deposit.txid = nil
        new_deposit.op_id = nil
        new_deposit.hex = nil
        new_deposit.description = params[:method]
        if new_deposit.save
            flash[:info] = "Operação de depósito solicitada. Verifique detalhes na tabela a direita. "
        else 
            flash[:info] = "Algo deu errado. Por favor, tente novamente!. "
        end
    end
    
    def cancel_order(user=nil,prm=Hash.new)
        if prm['id'].nil?
            @userOrder = current_user
            id = params[:id]
        else
            @userOrder = user
            id = prm['id']
        end
        begin
            
            @order = @userOrder.exchangeorder.find(id)
        rescue
            return {error: 'Ordem não encontrada'}
        end
        
        inicial_order = @order
        par = @order.par.split('/')
        if (@order.status != "open") and (@order.status != "executada")
            return {error: 'Ordem já cancelada'}
        end
        @order.status = "cancelled"
        if prm['id'].nil?
            flash[:info] = "Ordem cancelada! "
            recent_orders = table_orders(@order.par,@order.tipo)
            array_compare = recent_orders[:table]
            if array_compare.include?(inicial_order)
                count = 0
                array = array_compare.to_a
                result = Array.new
                array.each do |k|
                    count += 1
                    if k != inicial_order
                        result << k
                    end
                end
                broadcast_order(@order,{order_list: result})
            end
        end
        
        
        case @order.tipo
        when "buy"
            amount = (BigDecimal(@order.amount,8) * BigDecimal(@order.price,8)).to_s
            id = add_saldo(@userOrder,par[1],amount,"cancel_buy")
            Payment.exchange_payment(@userOrder,id,par[1],amount,"cancel_buy",@order.par)
        when "sell"
            id = add_saldo(@userOrder,par[0],@order.amount,"cancel_sell")
            Payment.exchange_payment(@userOrder,id,par[0],@order.amount,"cancel_sell",@order.par)
        end
        @id = @order.id
        @order.save
        if !prm['id'].nil?
            return @order
        end
    end
    
    def table_orders(pair,type)
        resp = Hash.new
        case type
        when "buy"
            resp[:table] = Exchangeorder.where("par = :str_par AND tipo = :tupe AND status = :stt", {str_par: "#{pair}", tupe: "buy", stt: "open"}).order(price: :desc).limit(15)
        when "sell"
            resp[:table] = Exchangeorder.where("par = :str_par AND tipo = :tupe AND status = :stt", {str_par: "#{pair}", tupe: "sell", stt: "open"}).order(price: :asc).limit(15)
        when nil        
            resp[:bid] = Exchangeorder.where("par = :str_par AND tipo = :tupe AND status = :stt", {str_par: "#{pair}", tupe: "buy", stt: "open"}).order(price: :desc).limit(25)
            resp[:ask] = Exchangeorder.where("par = :str_par AND tipo = :tupe AND status = :stt", {str_par: "#{pair}", tupe: "sell", stt: "open"}).order(price: :asc).limit(25)
        end
        resp
    end
    

    def open_orders
        if session[:current_place] == "overview"
            render :json => json_last_price
        end
    end
    
    def pairExists(pair)
        EXCHANGE_PARES.each do |exnchange_pair|
            if pair.upcase == exnchange_pair.tr(" ","").upcase
                return true
            elsif "#{pair.split("/").last}/#{pair.split("/").first}" == exnchange_pair.tr(" ","").upcase
                return true
            end
        end
        return false
    end
    
    def create_order(*args)
        label_bool = true
        isApi = false
        if args.count >= 1
            isApi = true
            if current_user.nil?
                order = User.find(args[0][:user]).exchangeorder.new
            else
                order = current_user.exchangeorder.new
            end
            @paramers = Hash.new
            @paramers[:coin1] = args[0][:pair].tr(" ","").split("/")[0]
            @paramers[:coin2] = args[0][:pair].tr(" ","").split("/")[1]
            @paramers[:type] = args[0][:type]
            
            order.par = ("#{@paramers[:coin1]}/#{@paramers[:coin2]}").upcase
            if !(pairExists(order.par))
                return {error: 'Par não suportado'}
            end
            order.tipo = args[0][:type]
            amount_str = args[0][:amount].tr(",",".")
            total_amount_instant = "%0.8f" % amount_str
            order.amount = args[0][:amount]

            #Definição de preço, caso seja instant ou não
            if args[0][:price].nil?
                case args[0][:type]
                when "buy"
                    order_open = Exchangeorder.where("par = :str_par AND tipo = :tupe AND status = :stt", {str_par: order.par, tupe: "sell", stt: "open"}).order(price: :asc).limit(1)[0]
                    if order_open.nil?
                        flash[:info] = "Não disponível. "
                        return
                    end
                    order.price = order_open.price
                    label_message = "comprar"
                    label_currency = @paramers[:coin1]
                when "sell"
                    order_open = Exchangeorder.where("par = :str_par AND tipo = :tupe AND status = :stt", {str_par: order.par, tupe: "buy", stt: "open"}).order(price: :desc).limit(1)[0]
                    if order_open.nil?
                        flash[:info] = "Não disponível. "
                        return
                    end
                    order.price = order_open.price
                    label_message = "vender"
                    label_currency = @paramers[:coin2]
                end
                if BigDecimal(order_open.amount,8) < BigDecimal(order.amount,8)
                    order.amount = order_open.amount
                    label_bool = false
                    flash[:info] = "Você tentou #{label_message} mais #{label_currency} do que a ordem no preço indicado tinha disponível. Sua operação foi reajustada para a quantidade total disponível de #{order.amount} #{label_currency}. Caso queira realizar mais operações instantâneas neste par, utilize o formulário novamente. "
                end
            else
                order.price = args[0][:price]
                case args[0][:type]
                when "buy"
                    label_message = "comprar"
                    label_currency = @paramers[:coin1]
                when "sell"
                    label_message = "vender"
                    label_currency = @paramers[:coin2]
                end
            end
            order.status = "open"
        else
            @paramers = params
            order = parseOrder(@paramers)
        end
        if current_user.nil?
            user = User.find(args[0][:user])
            saldos = eval(get_saldo(user))
        else
            saldos = eval(get_saldo(current_user))
        end
        order.has_execution = false
        total_value = BigDecimal(order.amount,8) * BigDecimal(order.price,8)
        case @paramers[:type]
        when "buy"
            compare_value = total_value
            saldo = saldos[@paramers[:coin2]]
            discount_currency = @paramers[:coin2]
            operation = "exchange_buy"
            consulta_ordem_oposta = Exchangeorder.where("par = :str_par AND tipo = :tupe AND status = :stt AND price <= :preco", {str_par: order.par, tupe: "sell", stt: "open", preco: order.price}).order(price: :asc)
        when "sell"
            compare_value = order.amount
            saldo = saldos[@paramers[:coin1]]
            discount_currency = @paramers[:coin1]
            operation = "exchange_sell"
            consulta_ordem_oposta = Exchangeorder.where("par = :str_par AND tipo = :tupe AND status = :stt AND price >= :preco", {str_par: order.par, tupe: "buy", stt: "open", preco: order.price}).order(price: :desc)
        end
        if BigDecimal(saldo,8) >= BigDecimal(compare_value,8)
            if current_user.nil?
                id = add_saldo(user,discount_currency,compare_value.to_s,operation)
                Payment.exchange_payment(user,id,discount_currency,compare_value.to_s,"open_order_#{order.tipo}",order.par)
            else
                id = add_saldo(current_user,discount_currency,compare_value.to_s,operation)
                Payment.exchange_payment(current_user,id,discount_currency,compare_value.to_s,"open_order_#{order.tipo}",order.par)
            end
            
            
            
            check_active_orders(order,consulta_ordem_oposta,@paramers[:type])
            if isApi
                return order
            end
            if label_bool
                flash[:info] = "Ordem adicionada ao livro! "
            end
        else
            if !(args.count >= 1)
                flash[:info] = "Não há saldo para iniciar esta negociação "
            else
                return {error: "Não há saldo para iniciar esta negociação "}
            end
        end
        @order = order
    end
    
    private
    
    def json_last_price
        result = Hash.new
        EXCHANGE_PARES.each do |k|
            par = k.tr(" ", "")
            result["#{par}_buy"] = last_price(par,"buy","executada")

app/helpers/exchange_helper.rb
module ExchangeHelper
end

app/views/exchange/_bank_deposit_form.html.erb
<%= form_tag(deposit_verify_new_path, disabled: true, remote: true, class: "directUpload",format: :js ,method: :post, data: { 'form-data' => (@s3_direct_post.fields), 'url' => @s3_direct_post.url, 'host' => URI.parse(@s3_direct_post.url).host }) %>
<div class="row">
    <div class="col-md-12 col-xs-12">
  <div class="form-group">
    <div class="row">
        <div class="col-md-12 col-xs-12">
          <fieldset>
            <legend><h7>Detalhes do depósito</h7></legend>
            Valor total: <b><%= @deposit.volume %> <%= @deposit.network %></b><br>
            Tipo: <b><%= @deposit.description %></b><br>
            Comissão: <b><%= b = BigDecimal(@deposit.volume,8) * 0.01 %> <%= @deposit.network %></b>
          </fieldset>
        <fieldset>
            <legend><%= label_tag :deposit_photo, "Comprovante" %></legend>
            <p>Caso seu comprovante seja digital, imprima-o e assine, colocando também seu <b>CPF</b> de forma legível.<br>
            Após o envio, espere a resposta de nossa equipe, ao verificarmos seu depósito, será enviado um email para você.<br>
            Seu arquivo pode ser uma simples foto do comprovante de depósito / transferência bancária devidamente assinado.
            <%= file_field_tag :deposit_photo, required: true %></p>
        </fieldset>
        </div>
    </div>
    <%= hidden_field_tag :id, @deposit.id %>
    
  </div>

    <%= submit_tag "Submeter", class: 'submit_button_active btn btn-primary btn-lg' %>
  <br/><br/>
  
  <script>
$(function aws() {
  $('*').find("input:file").each(function(i, elem) {
    var fileInput    = $(elem);
    var form         = $(fileInput.parents('form:first'));
    var submitButton = $('.submit_button_active');
    var progressBar  = $(`<div class='bar ${fileInput.prop("name")}'></div>`);
    var barContainer = $(`<div class='progress ${fileInput.prop("name")}'></div>`).append(progressBar);
    fileInput.after(barContainer);
    console.log("começando")
    fileInput.fileupload({
      fileInput:       fileInput,
      url:             "https://cptcambio.s3.us-east-2.amazonaws.com/",
      //url:             form.data('url'),
      type:            'POST',
      autoUpload:       true,
      formData:         form.data('form-data'),
      paramName:        'file', // S3 does not like nested name fields i.e. name="user[avatar_url]"
      dataType:         'XML',  // S3 returns XML if success_action_status is set to 201
      replaceFileInput: false,
      progressall: function (e, data) {
        var progress = parseInt(data.loaded / data.total * 100, 10);
        progressBar.css('width', progress + '%')
      },
      start: function (e) {
        submitButton.prop('disabled', true);

        progressBar.
          css('background', 'green').
          css('display', 'block').
          css('width', '0%').
          text("Carregando...");
      },
      done: function(e, data) {
        submitButton.prop('disabled', false);
        progressBar.text("Upload completo");

        // extract key and generate URL from response
        var key   = $(data.jqXHR.responseXML).find("Key").text();
        var url   = '//' + form.data('host') + '/' + key;
        //var url = 'cptcambio.s3.us-east-2.amazonaws.com/' + key

        // create hidden field
        var input = $("<input />", { type:'hidden', name: fileInput.attr('name'), value: url })
        form.append(input);
      },
      fail: function(e, data) {
        submitButton.prop('disabled', false);

        progressBar.
          css("background", "red").
          text("Failed");
      }
    });
  });
});
</script>

app/views/exchange/_index_ticker.html.erb
<div align="center" class="ticker_index row no-padding">
    <div class=" col-md-12 col-xs-12 ticker_margin no-padding">
        <div class="row collumn-block">
            <% MOEDAS_ATIVAS.each do |m| %>
            <% if m != "BRL" and m != "BTC" %>
            <div class="col-md-3 col-xs-3 col-lg-2 ticker_block">
                    <div class="row" class="ticker-list">
                        <div class="col-md-12 col-xs-12"><h4 class="white no-margin lesser-font-h4"><%= MOEDAS_ATIVAS_NAMES[m] %> (<%= m %>)</h4></div>
                    </div>
                    <% EXCHANGE_PARES.each do |pair| %>
                        <% compare = pair.tr(" ","") %>
                        <% if compare.split("/")[0] == m %>
                        <% price_cent = price_percentage(compare)%>
                            <div class="row" data-pair="<%= compare.tr("/","_") %>">
                                <div class="col-md-6 col-xs-5 white"><span title="<%= pair %> Cotação atual"><b class="ticker_index_price_<%= compare.tr("/","_") %> ticker-price"><%= last_price(compare,nil,nil)%></b></span></div>
                                <div class="col-md-3 col-xs-3 white"><b><%= compare.split("/")[1] %></b></div>
                                <div class="col-md-3 col-xs-4"><span title="<%= pair %> Variação (24h)" class="<%= color_type_percentage(price_cent.tr(",",".")) %> ticker_percentage_<%= pair.tr("/","_").tr(" ","") %>"><%= price_cent %>%</span></div>
                            </div>
                        <% end %>
                    <% end %>
            </div>
            <% end %>
        <% end %>
        </div>
    </div>
</div>

app/views/exchange/_instant_buy.html.erb
<div class="well">
<%= label_tag :operation, "Desejo:" %>
<div class="btn-group" data-toggle="buttons">
  <label data-type="buy" class="btn btn-primary active buttonType buttonSmall">
    <input type="radio" name="options" id="option1" autocomplete="off" checked> Comprar
  </label>
  <label data-type="sell" class="btn btn-primary buttonType buttonSmall">
    <input type="radio"  name="options" id="option2" autocomplete="off"> Vender
  </label>
</div>

<%= form_tag '/exchange/instant', remote: true, class: "exchange_form_element" %>
<%= hidden_field_tag :type, "buy", class: "hidden_type_order" %>
<div class="form-group">
    <div class="row">
        <div class="col-md-10">
            <%= label_tag :currency_base, "Com o par:" %>
            <%= select_tag :currency_base, options_for_select(EXCHANGE_PARES), :prompt => "Selecione o par" ,class: "pair-control form-control" %>
        </div>
    </div>
</div>
<div class="form-group margin-exchange">
    <div class="row">
        <div class="col-md-10">
            <h4><%= label_tag :amount, "Quantidade" %></h4>
            <%= text_field_tag :amount, nil, placeholder: "0.00000000", title: 'Utilize "." (ponto) como separador das casas decimais' , required: true ,class: "amount_input_instant form-control" %>
        </div>
    </div>
</div>
<div class="form-group">
    <h6><k class="valor_total">* Preço atual: </h6>
    <div class="row">
        <div class="col-md-10" data-toggle="tooltip" data-placement="right" title="<%= HELPER_TEXT["price-instant"] %>">
            <%= text_field_tag :instant_price, nil, placeholder: "0.00000000", required: false ,class: "actual_price_form form-control", disabled: true %></k>
        </div>
    </div>
</div>
<div class="form-group">
    <h6><k class="receber">Receber:</k> <b class="receber_instant"></b></h6>
</div>
<div class="form-group">
    <h6><k class="valor_total">Valor total:</k> <b class="total_instant"></b></h6>
</div>
<div class="form-group">
    <div class="row">
        <div class="col-md-8">
            <%= submit_tag "Submeter", class: "form-control withdrawal_button instant_submit" %>
        </div>
    </div>
</div>
<h6>* Devido a volatilidade do mercado, o preço pode variar muito em pequenos intervalos de tempo.</h6>
</form>

</div>

<script>
$(".buttonType").click(function(){
    $('#type').prop("value",$(this).data("type"))
    calc()
})
$( ".amount_input_instant" ).keyup(function() {
    element = $(".amount_input_instant")
    element.val((element.val()).replace(/[,]+/,'.'));
    element.val((element.val()).replace(/[.]+/,"."));
    element.val((element.val()).replace(/[^0-9\,.]/g,''));
    estimate();
    string = $(this).val();
    points = 0
    formated = ""
    for (var i = 0, len = string.length; i < len; i++) {
      if (string.charAt(i) == "."){
          points = points + 1
      }
      if (points <= 1){
        if ((string.charAt(i) != ".") && (points == 1)){
            if (formated.split(".")[1].length >= 8){
                $(this).val(formated)   
            }else{
                formated += string.charAt(i)
            }
        } else {
         formated += string.charAt(i)   
        }
      } else{
        $(this).val(formated)
      }
      
    }
    calc() 
});
// Contagem de casas decimais de um "value"
countDecimals = function(value) {
    if (Math.floor(value) !== value)
        return value.toString().split(".")[1].length || 0;
    return 0;
}

$(document).ready(function(){
		   $('[data-toggle="tooltip"]').tooltip();
});
function estimate(){
    elemento = $( ".pair-control" )
    a = elemento.find(":selected").text().replace(/ /,'')
    b = a.replace(/ /,'')
    quantity = parseFloat($( ".amount_input_instant" ).val().replace(",","."));
    price = parseFloat($(".actual_price_form").val().replace(",",".").split(" ")[0]);
    if (b == "Selecioneopar"){
        currency1 = ""
        currency2 = ""
    } else {
        pair = b.split("/");
        currency1 = pair[0];
        currency2 = pair[1];
    }
    
    
    if ($('#type').prop("value") == "buy"){
      discount = (quantity * 0.005).toFixed(8);
      receive = (quantity - discount).toFixed(8);
      total = (price * quantity).toFixed(8);
      
      $(".receber_instant").html(receive + " " + currency1);
      $(".total_instant").html(total + " " + currency2);
    }else{
      total = (price * quantity).toFixed(8);
      discount = (total * 0.005).toFixed(8);
      receive = (total - discount).toFixed(8);
      
      $(".receber_instant").html(receive + " " + currency2);
      $(".total_instant").html(total + " " + currency2);
    }
}
function calc(){
    elemento = $( ".pair-control" )
    if (elemento.find(":selected").text() == "Selecione o par"){
        $(".actual_price_form").val("Escolha um par!");
        return
    } else {
        a = elemento.find(":selected").text().replace(/ /,'')
        b = a.replace(/ /,'')
        $('.actual_price_form').data("pair",b)
        if ($('#type').prop("value") == "buy"){
          tipo = "buy"
        } else {
          tipo = "sell"
        };
        
        $.ajax({
        url: "instant_buy_price/" + b + '/' + tipo,
        cache: false,
        type: "GET",
        success: function(response) {
            $(".actual_price_form").val(response);
            price = response
            a = elemento.find(":selected").text().replace(/ /,'')
            b = a.replace(/ /,'')
            if (price == "Não disponível."){
              $('.instant_submit').prop("disabled",true)
            }else {
              $('.instant_submit').prop("disabled",false)
            }
            
            estimate();
        },
        error: function(xhr) {
            
        }});
    }
}

$( ".pair-control" ).change(function() {
    calc()
});
$( ".amount_input_instant" ).keyup(function() {
    
});
</script>

app/views/exchange/_open_orders.html.erb
<div class="col-md-6 col-xs-12 complete-table table-responsive">
        <table class="table table-hover table-sm table-striped">
        <tr>
            <th colspan="5" class="text-center">Suas ordens Abertas <%= "(#{session[:currency1]}/#{session[:currency2]})" %></th>
        </tr>
        <tr class="active">
            <th class="small_lines">
                Preço
            </th>
            <th class="small_lines">
                Volume
            </th>
            <th class="small_lines">
                Tipo
            </th>
            <th class="small_lines">
                Execuções
            </th>
            <th class="small_lines">
                Cancelar ordem
            </th>
        </tr>
        <% a = current_user.exchangeorder.where("par = :str_par AND status = :stt", {str_par: "#{session[:currency1]}/#{session[:currency2]}", stt: "open"}).order(id: :desc).page params[:page] %>
        <% a.each do |m| %>
        <tr>
            <td class="small_lines">
                <%= m.price %> <%= session[:currency2] %>
            </td>
            <td class="small_lines">
                <%= m.amount %> <%= session[:currency1] %>
            </td>
            <td class="small_lines">
                <% if m.tipo == "buy" %>
                Compra
                <% else %>
                Venda
                <% end %>
            </td>
            <td class="small_lines">
                <% if m.has_execution == true %>
                <i class="fa fa-check" aria-hidden="true"></i>
                <% else %>
                <i class="fa fa-times" aria-hidden="true"></i>
                <% end %>
            </td>
            <td class="small_lines">
                <button type="button" data-order-id="<%= m.id %>" class="btn btn-danger cancel-order"><i class="fa fa-ban" aria-hidden="true"></i></button>
            </td>
        </tr>
        <% end %>
    </table>
    <%= paginate a, left: 1, right: 3, remote: true %>
    </div>
    
    
    <script>
    $('.cancel-order').click(function (){
        r = confirm("Deseja cancelar esta ordem?");
        if (r==true)
          {
          $.ajax({
            url: ("/exchange/order/cancel/" + $(this).data("order-id")),
            cache: false,
            type: "POST",
            success: function(response) {
                
            },
            error: function(xhr) {
                
            }
            })
          }
        
        
    })
</script>

app/views/exchange/_orders.erb
<div class="row">
    <div class="col-md-4 col-xs-4 sell-table container">
        <%= render 'exchange/order_form' %>
    </div>
    <div class="open_orders_table">
        <%= render 'exchange/orders_table' %>
    </div>
</div>
<div class="row">
    <div class="user_orders">
        <%= render 'exchange/open_orders' %>
    </div>
    <div class="recent_orders">
        <%= render 'exchange/recent_orders' %>
    </div>
</div>

app/views/exchange/_recent_orders.html.erb
<div class="col-md-12 col-xs-12 complete-table table-responsive">
        <table class="table  <%= "#{session[:currency1]}_#{session[:currency2]}" %>_executed">
        <tr>
            <th colspan="2" class="text-center">Ordens executadas <%= "(#{session[:currency1]}/#{session[:currency2]})" %></th>
        </tr>
        <tr class="">
            <th class="small_lines">
                Preço
            </th>
            <th class="small_lines">
                Volume
            </th>
        </tr>
        <% Exchangeorder.where("par = :str_par AND status = :stt", {str_par: "#{session[:currency1]}/#{session[:currency2]}", stt: "executada"}).order("updated_at DESC").limit(20).each do |m| %>
        <tr>
            <td class="small_lines">
                <%= m.price %> <%= session[:currency2] %>
            </td>
            <td class="small_lines">
                <%= m.amount %> <%= session[:currency1] %>
            </td>
        </tr>
        <% end %>
    </table>
    </div>

app/views/exchange/cancel_order.js.erb
$('.centered-flash').html('<%= escape_javascript( render( :partial => 'warns/centered_flash') ) %>');
$( ".saldos" ).html( "<%= escape_javascript( render( :partial => "layouts/saldos") ) %>" );
$( ".user_orders" ).html( "<%= escape_javascript( render( :partial => "exchange/open_orders") ) %>" );
$("#<%= @id %>").html("");

app/views/exchange/open_orders.js.erb
<% if session[:current_place] == "business"%>
$('.open_orders_table').html( "<%= escape_javascript( render( :partial => "exchange/orders_table" )) %>" );
$('.recent_orders').html( "<%= escape_javascript( render( :partial => "exchange/recent_orders" )) %>" );
<% end %>